CREATE EXTERNAL FILE FORMAT [GzipCSVFileFormat]
    WITH (
    FORMAT_TYPE = DELIMITEDTEXT,
    FORMAT_OPTIONS (FIELD_TERMINATOR = N',', STRING_DELIMITER = N'"', DATE_FORMAT = N'dd/MM/yyyy', USE_TYPE_DEFAULT = True, FIRST_ROW = 2, ENCODING = N'UTF8'),
    DATA_COMPRESSION = N'org.apache.hadoop.io.compress.GzipCodec'
    );

