CREATE EXTERNAL FILE FORMAT [TextFile]
    WITH (
    FORMAT_TYPE = DELIMITEDTEXT,
    FORMAT_OPTIONS (FIELD_TERMINATOR = N',', STRING_DELIMITER = N'"', DATE_FORMAT = N'dd/MM/yyyy', FIRST_ROW = 2, ENCODING = N'UTF8')
    );

