CREATE TABLE [HR_data].[Basic_User] (
    [User_Status]      VARCHAR (20)  NULL,
    [UserID]           INT           NULL,
    [UserName]         VARCHAR (50)  NULL,
    [FirstName]        VARCHAR (30)  NULL,
    [MiddleName]       VARCHAR (30)  NULL,
    [LastName]         VARCHAR (30)  NULL,
    [Gender]           VARCHAR (20)  NULL,
    [Email]            VARCHAR (50)  NULL,
    [Manager]          VARCHAR (50)  NULL,
    [HR]               VARCHAR (50)  NULL,
    [Department]       VARCHAR (50)  NULL,
    [Jobcode]          INT           NULL,
    [Division]         VARCHAR (50)  NULL,
    [UserLocation]     VARCHAR (50)  NULL,
    [Timezone]         VARCHAR (20)  NULL,
    [HireDate]         DATE          NULL,
    [EmpID]            INT           NULL,
    [Title]            VARCHAR (20)  NULL,
    [BusinessPhone]    VARCHAR (50)  NULL,
    [Fax]              VARCHAR (50)  NULL,
    [Address1]         VARCHAR (300) NULL,
    [Address2]         VARCHAR (300) NULL,
    [City]             VARCHAR (50)  NULL,
    [UserState]        VARCHAR (50)  NULL,
    [Zip]              INT           NULL,
    [Country]          VARCHAR (50)  NULL,
    [Review_frequency] VARCHAR (20)  NULL,
    [Last_Review_date] DATE          NULL,
    [Custom1]          VARCHAR (50)  NULL,
    [Custom2]          VARCHAR (50)  NULL,
    [Custom3]          VARCHAR (50)  NULL,
    [Custom4]          VARCHAR (50)  NULL,
    [Custom5]          VARCHAR (50)  NULL,
    [Custom6]          VARCHAR (50)  NULL,
    [Custom7]          VARCHAR (50)  NULL,
    [Custom8]          VARCHAR (50)  NULL,
    [Custom9]          VARCHAR (50)  NULL,
    [Custom10]         VARCHAR (50)  NULL,
    [Custom11]         VARCHAR (50)  NULL,
    [Custom12]         VARCHAR (50)  NULL,
    [Custom13]         VARCHAR (50)  NULL,
    [Custom14]         VARCHAR (50)  NULL,
    [Custom15]         VARCHAR (50)  NULL,
    [Matrix_Manager]   VARCHAR (100) NULL,
    [Default_locale]   VARCHAR (100) NULL,
    [Proxy]            VARCHAR (50)  NULL,
    [Custom_Manager]   VARCHAR (100) NULL,
    [Second_Manager]   VARCHAR (100) NULL,
    [OnboardingID]     INT           NULL,
    [Source_name]      VARCHAR (50)  NULL,
    [Source_file_Name] VARCHAR (100) NULL,
    [Load_date]        DATE          NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

