CREATE TABLE [HR_data].[Job_info] (
    [Department]          VARCHAR (50)  NULL,
    [Business_Unit]       VARCHAR (50)  NULL,
    [Company]             INT           NULL,
    [Standard_hours]      INT           NULL,
    [Employee_class]      VARCHAR (50)  NULL,
    [Employment_type]     VARCHAR (50)  NULL,
    [EventDate]           DATE          NULL,
    [EventReason]         VARCHAR (50)  NULL,
    [Custom_string10]     VARCHAR (50)  NULL,
    [ManagerID]           VARCHAR (50)  NULL,
    [Position]            VARCHAR (50)  NULL,
    [Position_entry_date] DATE          NULL,
    [Division]            VARCHAR (50)  NULL,
    [Sick_Pay_Supplement] VARCHAR (50)  DEFAULT ('Default Scheme') NULL,
    [Job_Location]        VARCHAR (50)  NULL,
    [CostCentre]          VARCHAR (50)  NULL,
    [FTE]                 VARCHAR (50)  NULL,
    [IsFTE]               VARCHAR (20)  NULL,
    [Job_entry_date]      DATE          NULL,
    [Custom_string13]     VARCHAR (50)  NULL,
    [JobTitle]            VARCHAR (50)  NULL,
    [Regular_Temp]        VARCHAR (50)  NULL,
    [WorkscheduleCode]    VARCHAR (50)  NULL,
    [PayScaleGroup]       VARCHAR (50)  NULL,
    [PayScaleArea]        VARCHAR (50)  NULL,
    [PayScaleLevel]       VARCHAR (50)  NULL,
    [PayScaleType]        VARCHAR (50)  NULL,
    [WorkingDaysPerWeek]  VARCHAR (50)  NULL,
    [HolidayCalendarCode] VARCHAR (50)  NULL,
    [JobEndDate]          DATE          NULL,
    [Operation]           VARCHAR (50)  NULL,
    [Source_name]         VARCHAR (50)  NULL,
    [Source_file_Name]    VARCHAR (100) NULL,
    [Load_date]           DATE          NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

