CREATE TABLE [dbo].[DIM_WOW_VENDOR] (
    [Vendor]               VARCHAR (60) NULL,
    [V]                    VARCHAR (60) NULL,
    [Street Name]          VARCHAR (60) NULL,
    [Tax Number 2]         VARCHAR (60) NULL,
    [Check digit -ILN]     VARCHAR (60) NULL,
    [Created on]           VARCHAR (60) NULL,
    [Currency]             VARCHAR (60) NULL,
    [Deletion Indicator]   VARCHAR (60) NULL,
    [VN Vendor]            VARCHAR (60) NULL,
    [Address]              VARCHAR (60) NULL,
    [Location]             VARCHAR (60) NULL,
    [CAM: City District]   VARCHAR (60) NULL,
    [Country]              VARCHAR (60) NULL,
    [D-U-N-S Number]       VARCHAR (60) NULL,
    [Fax Number]           VARCHAR (60) NULL,
    [One-Time Account]     VARCHAR (60) NULL,
    [Industry]             VARCHAR (60) NULL,
    [Name]                 VARCHAR (60) NULL,
    [Name 2]               VARCHAR (60) NULL,
    [Name 3]               VARCHAR (60) NULL,
    [Trading partner]      VARCHAR (60) NULL,
    [Telephone 1]          VARCHAR (60) NULL,
    [Site]                 VARCHAR (60) NULL,
    [P.O. Box]             VARCHAR (60) NULL,
    [CAM: PO Box Location] VARCHAR (60) NULL,
    [Postal Code]          VARCHAR (60) NULL,
    [CAM:POBox PostalCode] VARCHAR (60) NULL,
    [CAM:PstCde(Geo-Rel.)] VARCHAR (60) NULL,
    [Geo-precision]        VARCHAR (60) NULL,
    [Region]               VARCHAR (60) NULL,
    [Sort Field]           VARCHAR (60) NULL,
    [NDC Contact Phone]    VARCHAR (60) NULL,
    [Indent (Flag)]        VARCHAR (60) NULL,
    [NDC Charge PLG to Ve] VARCHAR (60) NULL,
    [NDC Claim Contact Na] VARCHAR (60) NULL,
    [Mobile Number]        VARCHAR (60) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

