CREATE TABLE [dbo].[DIM_WOW_ARTICLE_OLD_18Mar2020] (
    [Article]              VARCHAR (50) NULL,
    [Description]          VARCHAR (50) NULL,
    [Vendor Pack Size]     VARCHAR (50) NULL,
    [TU pack size]         VARCHAR (50) NULL,
    [Scan Description]     VARCHAR (50) NULL,
    [Length]               VARCHAR (50) NULL,
    [Width]                VARCHAR (50) NULL,
    [Height]               VARCHAR (50) NULL,
    [Unit]                 VARCHAR (50) NULL,
    [Order Multiple]       VARCHAR (50) NULL,
    [Sellable Article]     VARCHAR (50) NULL,
    [Net contents]         VARCHAR (50) NULL,
    [Content unit]         VARCHAR (50) NULL,
    [Container Material T] VARCHAR (50) NULL,
    [Dangerous goods indi] VARCHAR (50) NULL,
    [Hazard goods indicat] VARCHAR (50) NULL,
    [General item categor] VARCHAR (50) NULL,
    [Order unit]           VARCHAR (50) NULL,
    [Ind. Std Desc.]       VARCHAR (50) NULL,
    [Season Year]          VARCHAR (50) NULL,
    [Season]               VARCHAR (50) NULL,
    [Article Type]         VARCHAR (50) NULL,
    [Base Unit]            VARCHAR (50) NULL,
    [EAN Number Type]      VARCHAR (50) NULL,
    [MCH Level 4]          VARCHAR (50) NULL,
    [MCH Level 3]          VARCHAR (50) NULL,
    [MCH Level 2]          VARCHAR (50) NULL,
    [MCH Level 1]          VARCHAR (50) NULL,
    [Valid From]           VARCHAR (50) NULL,
    [Country]              VARCHAR (50) NULL,
    [Sales unit]           VARCHAR (50) NULL,
    [Unit of Issue]        VARCHAR (50) NULL,
    [Subsection Number]    VARCHAR (50) NULL,
    [Comparative size UOM] VARCHAR (50) NULL,
    [Master Size UOM]      VARCHAR (50) NULL,
    [Master Size]          VARCHAR (50) NULL,
    [Warehouse Descriptio] VARCHAR (50) NULL,
    [Fine Department Numb] VARCHAR (50) NULL,
    [Coarse Departmnt No]  VARCHAR (50) NULL,
    [Tax Class Material]   VARCHAR (50) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

