CREATE TABLE [dbo].[DIM_WOW_ARTICLE_OLD_12April2020] (
    [Article]                 VARCHAR (50) NULL,
    [Description]             VARCHAR (50) NULL,
    [VendorPackSize]          VARCHAR (50) NULL,
    [TUPackSize]              VARCHAR (50) NULL,
    [Scan Description]        VARCHAR (50) NULL,
    [Length]                  VARCHAR (50) NULL,
    [Width]                   VARCHAR (50) NULL,
    [Height]                  VARCHAR (50) NULL,
    [Unit]                    VARCHAR (50) NULL,
    [OrderMultiple]           VARCHAR (50) NULL,
    [SellableArticle]         VARCHAR (50) NULL,
    [NetContents]             VARCHAR (50) NULL,
    [ContentUnit]             VARCHAR (50) NULL,
    [ContainerMaterial]       VARCHAR (50) NULL,
    [DangerousGoodsIndicator] VARCHAR (50) NULL,
    [HazardGoodsIndicat]      VARCHAR (50) NULL,
    [GeneralItemCategor]      VARCHAR (50) NULL,
    [OrderUnit]               VARCHAR (50) NULL,
    [IndStdDescription]       VARCHAR (50) NULL,
    [SeasonYear]              VARCHAR (50) NULL,
    [Season]                  VARCHAR (50) NULL,
    [ArticleType]             VARCHAR (50) NULL,
    [BaseUnit]                VARCHAR (50) NULL,
    [EANNumberType]           VARCHAR (50) NULL,
    [MCHLevel4]               VARCHAR (50) NULL,
    [MCHLevel3]               VARCHAR (50) NULL,
    [MCHLevel2]               VARCHAR (50) NULL,
    [MCHLevel1]               VARCHAR (50) NULL,
    [ValidFrom]               VARCHAR (50) NULL,
    [Country]                 VARCHAR (50) NULL,
    [SalesUnit]               VARCHAR (50) NULL,
    [UnitOfIssue]             VARCHAR (50) NULL,
    [SubsectionNumber]        VARCHAR (50) NULL,
    [ComparativeSizeUOM]      VARCHAR (50) NULL,
    [MasterSizeUOM]           VARCHAR (50) NULL,
    [MasterSize]              VARCHAR (50) NULL,
    [WarehouseDescriptio]     VARCHAR (50) NULL,
    [FineDepartmentNumb]      VARCHAR (50) NULL,
    [CoarseDepartmntNo]       VARCHAR (50) NULL,
    [TaxClassMaterial]        VARCHAR (50) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

