CREATE TABLE [dbo].[DIM_CALENDAR] (
    [CLNDR_DATE]         DATE         NULL,
    [LITRL_DATE]         VARCHAR (50) NULL,
    [WOCY]               INT          NULL,
    [CW_START_DATE]      DATE         NULL,
    [CW_END_DATE]        DATE         NULL,
    [POCY]               INT          NULL,
    [CP_START_DATE]      DATE         NULL,
    [CP_END_DATE]        DATE         NULL,
    [QOCY]               INT          NULL,
    [CQ_START_DATE]      DATE         NULL,
    [CQ_END_DATE]        DATE         NULL,
    [HOCY]               INT          NULL,
    [CH_START_DATE]      DATE         NULL,
    [CH_END_DATE]        DATE         NULL,
    [CY]                 INT          NULL,
    [CY_START_DATE]      DATE         NULL,
    [CY_END_DATE]        DATE         NULL,
    [DOW]                INT          NULL,
    [DAY_OF_MT]          INT          NULL,
    [FY]                 INT          NULL,
    [FY_START_DATE]      DATE         NULL,
    [FY_END_DATE]        DATE         NULL,
    [HOFY]               INT          NULL,
    [FH_START_DATE]      DATE         NULL,
    [FH_END_DATE]        DATE         NULL,
    [QOFY]               INT          NULL,
    [FQ_START_DATE]      DATE         NULL,
    [FQ_END_DATE]        DATE         NULL,
    [POFY]               INT          NULL,
    [FP_START_DATE]      DATE         NULL,
    [FP_END_DATE]        DATE         NULL,
    [WOFY]               INT          NULL,
    [WOFP]               INT          NULL,
    [FW_START_DATE]      DATE         NULL,
    [FW_END_DATE]        DATE         NULL,
    [BIGW_FY]            INT          NULL,
    [BIGW_FY_START_DATE] DATE         NULL,
    [BIGW_FY_END_DATE]   DATE         NULL,
    [BIGW_HOFY]          INT          NULL,
    [BIGW_FH_START_DATE] DATE         NULL,
    [BIGW_FH_END_DATE]   DATE         NULL,
    [BIGW_QOFY]          INT          NULL,
    [BIGW_FQ_START_DATE] DATE         NULL,
    [BIGW_FQ_END_DATE]   DATE         NULL,
    [BIGW_POFY]          INT          NULL,
    [BIGW_FP_START_DATE] DATE         NULL,
    [BIGW_FP_END_DATE]   DATE         NULL,
    [BIGW_WOFY]          INT          NULL,
    [BIGW_WOFP]          INT          NULL,
    [BIGW_FW_START_DATE] DATE         NULL,
    [BIGW_FW_END_DATE]   DATE         NULL,
    [DIM_LOAD_DATE]      DATETIME     NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([CLNDR_DATE]));

