CREATE TABLE [dbo].[DIM_STORES] (
    [Corp_Lvl1]             VARCHAR (20)   NULL,
    [Corp_Lvl1_Name]        VARCHAR (100)  NULL,
    [Corp_Lvl2]             VARCHAR (20)   NULL,
    [Corp_Lvl2_Name]        VARCHAR (100)  NULL,
    [Corp_Lvl3]             VARCHAR (20)   NULL,
    [Corp_Lvl3_Name]        VARCHAR (100)  NULL,
    [Corp_Lvl4]             VARCHAR (20)   NULL,
    [Corp_Lvl4_Name]        VARCHAR (100)  NULL,
    [Store]                 VARCHAR (20)   NOT NULL,
    [Name]                  VARCHAR (100)  NULL,
    [Adress_Line_1]         NVARCHAR (250) NULL,
    [Addres_Line_2]         VARCHAR (250)  NULL,
    [City]                  VARCHAR (50)   NULL,
    [State]                 VARCHAR (20)   NULL,
    [ZIP]                   VARCHAR (20)   NULL,
    [Tel_1]                 VARCHAR (20)   NULL,
    [Manager]               VARCHAR (20)   NULL,
    [Fax]                   VARCHAR (20)   NULL,
    [Currency]              VARCHAR (10)   NULL,
    [Tax1]                  VARCHAR (20)   NULL,
    [Tax2]                  VARCHAR (20)   NULL,
    [Tax3]                  VARCHAR (20)   NULL,
    [Tax4]                  VARCHAR (20)   NULL,
    [Dealer_Operated]       VARCHAR (20)   NULL,
    [NU1]                   VARCHAR (20)   NULL,
    [Store_Internal_Number] VARCHAR (20)   NULL,
    [Country]               VARCHAR (20)   NULL,
    [Store_Tax_No]          VARCHAR (20)   NULL,
    [Store_Group]           VARCHAR (20)   NULL,
    [DEACTIVATED]           VARCHAR (20)   NULL,
    [ACTIVATION_DATE]       VARCHAR (20)   NULL,
    [TIMESTAMP]             DATETIME       NULL,
    [start_date]            DATE           NULL,
    [end_date]              DATE           NULL,
    [load_date]             DATETIME       NULL,
    [source_file_name]      VARCHAR (200)  NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([Store]));

