CREATE TABLE [dbo].[EG_ENVOY_PITRJOURNAL_HDR] (
    [STORE]              VARCHAR (200) NULL,
    [POS_NUM]            VARCHAR (200) NULL,
    [DRAWER_NUM]         VARCHAR (200) NULL,
    [BUSINESS_DAY]       VARCHAR (200) NULL,
    [SHIFT_NUM]          VARCHAR (200) NULL,
    [TRANSACTION_NUM]    VARCHAR (200) NULL,
    [TRANSACTION_DATE]   VARCHAR (200) NULL,
    [TRANSACTION_TIME]   VARCHAR (200) NULL,
    [CASHIER_ID]         VARCHAR (200) NULL,
    [CUSTOMER_ID]        VARCHAR (200) NULL,
    [TIMESTAMP]          VARCHAR (200) NULL,
    [LOADED]             VARCHAR (200) NULL,
    [REGISTER_ID]        VARCHAR (200) NULL,
    [REPORT_KEY]         VARCHAR (200) NULL,
    [DETAIL_KEY]         VARCHAR (200) NULL,
    [JOURNAL_KEY]        VARCHAR (200) NULL,
    [JOURNAL_TYPE]       VARCHAR (200) NULL,
    [CODE]               VARCHAR (200) NULL,
    [POS_CODE]           VARCHAR (200) NULL,
    [MULTIPLIER]         VARCHAR (200) NULL,
    [SERVICE_LEVE]       VARCHAR (200) NULL,
    [POS_SERVICE_LEVEL]  VARCHAR (200) NULL,
    [AMOUNT]             VARCHAR (200) NULL,
    [QUANTITY]           VARCHAR (200) NULL,
    [OUTSIDE_SALES_FLAG] VARCHAR (200) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

