CREATE TABLE [dbo].[EG_VENDOR_ARTICLE_EAN] (
    [VENDOR_NAME]            VARCHAR (200) NULL,
    [VENDOR_NO]              VARCHAR (50)  NULL,
    [EFFECTIVE_DATE]         VARCHAR (20)  NULL,
    [TUN]                    VARCHAR (50)  NULL,
    [EAN]                    VARCHAR (50)  NULL,
    [FULL_DESCRIPTION]       VARCHAR (200) NULL,
    [RESTRICTED_DESCRIPTION] VARCHAR (200) NULL,
    [UOM]                    VARCHAR (50)  NULL,
    [SEGMENT_NUMBER]         VARCHAR (50)  NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

