CREATE TABLE [dbo].[EG_WOW_ARTICLE_EAN_OLD] (
    [ARTICLE_NO]   VARCHAR (50)  NULL,
    [ARTICLE_DESC] VARCHAR (200) NULL,
    [EAN]          VARCHAR (50)  NULL,
    [TUN]          VARCHAR (50)  NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

