CREATE TABLE [dbo].[EG_WOW_SITE_SOH] (
    [SITE_NO]      NVARCHAR (250) NULL,
    [SITE_NAME]    NVARCHAR (200) NULL,
    [SOH_DATE]     NVARCHAR (250) NULL,
    [ARTICLE_NO]   NVARCHAR (250) NULL,
    [ARTICLE_DESC] NVARCHAR (250) NULL,
    [STOCK_QTY]    NVARCHAR (250) NULL,
    [FILE_NAME]    NVARCHAR (250) NULL,
    [LOAD_DATE]    DATETIME       NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

