CREATE TABLE [dbo].[Jda_Product] (
    [DBKey]                      BIGINT        NULL,
    [UPC]                        VARCHAR (20)  NULL,
    [ID]                         VARCHAR (20)  NULL,
    [Name]                       VARCHAR (100) NULL,
    [Abbrev name]                VARCHAR (20)  NULL,
    [Size]                       FLOAT (53)    NULL,
    [UOM]                        VARCHAR (5)   NULL,
    [Manufacturer]               VARCHAR (255) NULL,
    [Brand]                      VARCHAR (255) NULL,
    [Supplier]                   VARCHAR (255) NULL,
    [Category]                   VARCHAR (255) NULL,
    [Subcategory]                VARCHAR (255) NULL,
    [Height]                     FLOAT (53)    NULL,
    [Width]                      FLOAT (53)    NULL,
    [Depth]                      FLOAT (53)    NULL,
    [Weight]                     FLOAT (53)    NULL,
    [Inner pack]                 INT           NULL,
    [Package style]              VARCHAR (10)  NULL,
    [Default merch style]        INT           NULL,
    [Color]                      BIGINT        NULL,
    [Fill pattern]               INT           NULL,
    [Shape ID]                   VARCHAR (50)  NULL,
    [Bitmap ID Override]         VARCHAR (255) NULL,
    [Bitmap ID Override Unit]    BIT           NULL,
    [Model Filename]             VARCHAR (255) NULL,
    [Model Filename Lookup]      BIGINT        NULL,
    [Automatic model]            INT           NULL,
    [Transparency]               FLOAT (53)    NULL,
    [Unit movement]              FLOAT (53)    NULL,
    [Price]                      FLOAT (53)    NULL,
    [Case cost]                  FLOAT (53)    NULL,
    [Unit cost]                  FLOAT (53)    NULL,
    [Tax code]                   INT           NULL,
    [Share]                      FLOAT (53)    NULL,
    [Case multiple]              FLOAT (53)    NULL,
    [Days supply]                FLOAT (53)    NULL,
    [Delivery schedule]          VARCHAR (50)  NULL,
    [Backroom stock]             FLOAT (53)    NULL,
    [Peak safety factor]         FLOAT (53)    NULL,
    [Pegholes]                   INT           NULL,
    [Peg ID]                     VARCHAR (100) NULL,
    [Peg span]                   INT           NULL,
    [Peghole X]                  FLOAT (53)    NULL,
    [Peghole Y]                  FLOAT (53)    NULL,
    [Peghole width]              FLOAT (53)    NULL,
    [Peghole 2 X]                FLOAT (53)    NULL,
    [Peghole 2 Y]                FLOAT (53)    NULL,
    [Peghole 2 width]            FLOAT (53)    NULL,
    [Peghole 3 X]                FLOAT (53)    NULL,
    [Peghole 3 Y]                FLOAT (53)    NULL,
    [Peghole 3 width]            FLOAT (53)    NULL,
    [X nesting]                  FLOAT (53)    NULL,
    [Y nesting]                  FLOAT (53)    NULL,
    [Z nesting]                  FLOAT (53)    NULL,
    [Minimum units]              INT           NULL,
    [Maximum units]              INT           NULL,
    [Front overhang]             FLOAT (53)    NULL,
    [Finger space Y]             FLOAT (53)    NULL,
    [Finger space X]             FLOAT (53)    NULL,
    [Jumble factor]              FLOAT (53)    NULL,
    [Case height]                FLOAT (53)    NULL,
    [Case width]                 FLOAT (53)    NULL,
    [Case depth]                 FLOAT (53)    NULL,
    [Case number high]           INT           NULL,
    [Case number wide]           INT           NULL,
    [Case number deep]           INT           NULL,
    [Case total number]          INT           NULL,
    [Case max high]              INT           NULL,
    [Tray height]                FLOAT (53)    NULL,
    [Tray width]                 FLOAT (53)    NULL,
    [Tray depth]                 FLOAT (53)    NULL,
    [Tray number high]           INT           NULL,
    [Tray number wide]           INT           NULL,
    [Tray number deep]           INT           NULL,
    [Tray total number]          INT           NULL,
    [Tray max high]              INT           NULL,
    [Display height]             FLOAT (53)    NULL,
    [Display width]              FLOAT (53)    NULL,
    [Display depth]              FLOAT (53)    NULL,
    [Display number high]        INT           NULL,
    [Display number wide]        INT           NULL,
    [Display number deep]        INT           NULL,
    [Display total number]       INT           NULL,
    [Display max high]           INT           NULL,
    [Alternate height]           FLOAT (53)    NULL,
    [Alternate width]            FLOAT (53)    NULL,
    [Alternate depth]            FLOAT (53)    NULL,
    [Alternate number high]      INT           NULL,
    [Alternate number wide]      INT           NULL,
    [Alternate number deep]      INT           NULL,
    [Alternate total number]     INT           NULL,
    [Alternate max high]         INT           NULL,
    [Loose height]               FLOAT (53)    NULL,
    [Loose width]                FLOAT (53)    NULL,
    [Loose depth]                FLOAT (53)    NULL,
    [Loose number high]          INT           NULL,
    [Loose number wide]          INT           NULL,
    [Loose number deep]          INT           NULL,
    [Loose total number]         INT           NULL,
    [MerchXMin]                  INT           NULL,
    [MerchXMax]                  INT           NULL,
    [MerchXUprights]             INT           NULL,
    [MerchXCaps]                 INT           NULL,
    [MerchXNumber]               INT           NULL,
    [MerchXSize]                 INT           NULL,
    [MerchYMin]                  INT           NULL,
    [MerchYMax]                  INT           NULL,
    [MerchYUprights]             INT           NULL,
    [MerchYCaps]                 INT           NULL,
    [MerchYNumber]               INT           NULL,
    [MerchYSize]                 INT           NULL,
    [MerchZMin]                  INT           NULL,
    [MerchZMax]                  INT           NULL,
    [MerchZUprights]             INT           NULL,
    [MerchZCaps]                 INT           NULL,
    [MerchZNumber]               INT           NULL,
    [MerchZSize]                 INT           NULL,
    [Desc1]                      VARCHAR (255) NULL,
    [Desc2]                      VARCHAR (255) NULL,
    [Desc3]                      VARCHAR (255) NULL,
    [Desc4]                      VARCHAR (255) NULL,
    [Desc5]                      VARCHAR (255) NULL,
    [Desc6]                      VARCHAR (255) NULL,
    [Desc7]                      VARCHAR (255) NULL,
    [Desc8]                      VARCHAR (255) NULL,
    [Desc9]                      VARCHAR (255) NULL,
    [Desc10]                     VARCHAR (255) NULL,
    [Desc11]                     VARCHAR (255) NULL,
    [Desc12]                     VARCHAR (255) NULL,
    [Desc13]                     VARCHAR (255) NULL,
    [Desc14]                     VARCHAR (255) NULL,
    [Desc15]                     VARCHAR (255) NULL,
    [Desc16]                     VARCHAR (255) NULL,
    [Desc17]                     VARCHAR (255) NULL,
    [Desc18]                     VARCHAR (255) NULL,
    [Desc19]                     VARCHAR (255) NULL,
    [Desc20]                     VARCHAR (255) NULL,
    [Desc21]                     VARCHAR (255) NULL,
    [Desc22]                     VARCHAR (255) NULL,
    [Desc23]                     VARCHAR (255) NULL,
    [Desc24]                     VARCHAR (255) NULL,
    [Desc25]                     VARCHAR (255) NULL,
    [Desc26]                     VARCHAR (255) NULL,
    [Desc27]                     VARCHAR (255) NULL,
    [Desc28]                     VARCHAR (255) NULL,
    [Desc29]                     VARCHAR (255) NULL,
    [Desc30]                     VARCHAR (255) NULL,
    [Desc31]                     VARCHAR (255) NULL,
    [Desc32]                     VARCHAR (255) NULL,
    [Desc33]                     VARCHAR (255) NULL,
    [Desc34]                     VARCHAR (255) NULL,
    [Desc35]                     VARCHAR (255) NULL,
    [Desc36]                     VARCHAR (255) NULL,
    [Desc37]                     VARCHAR (255) NULL,
    [Desc38]                     VARCHAR (255) NULL,
    [Desc39]                     VARCHAR (255) NULL,
    [Desc40]                     VARCHAR (255) NULL,
    [Desc41]                     VARCHAR (255) NULL,
    [Desc42]                     VARCHAR (255) NULL,
    [Desc43]                     VARCHAR (255) NULL,
    [Desc44]                     VARCHAR (255) NULL,
    [Desc45]                     VARCHAR (255) NULL,
    [Desc46]                     VARCHAR (255) NULL,
    [Desc47]                     VARCHAR (255) NULL,
    [Desc48]                     VARCHAR (255) NULL,
    [Desc49]                     VARCHAR (255) NULL,
    [Desc50]                     VARCHAR (255) NULL,
    [Value1]                     FLOAT (53)    NULL,
    [Value2]                     FLOAT (53)    NULL,
    [Value3]                     FLOAT (53)    NULL,
    [Value4]                     FLOAT (53)    NULL,
    [Value5]                     FLOAT (53)    NULL,
    [Value6]                     FLOAT (53)    NULL,
    [Value7]                     FLOAT (53)    NULL,
    [Value8]                     FLOAT (53)    NULL,
    [Value9]                     FLOAT (53)    NULL,
    [Value10]                    FLOAT (53)    NULL,
    [Value11]                    FLOAT (53)    NULL,
    [Value12]                    FLOAT (53)    NULL,
    [Value13]                    FLOAT (53)    NULL,
    [Value14]                    FLOAT (53)    NULL,
    [Value15]                    FLOAT (53)    NULL,
    [Value16]                    FLOAT (53)    NULL,
    [Value17]                    FLOAT (53)    NULL,
    [Value18]                    FLOAT (53)    NULL,
    [Value19]                    FLOAT (53)    NULL,
    [Value20]                    FLOAT (53)    NULL,
    [Value21]                    FLOAT (53)    NULL,
    [Value22]                    FLOAT (53)    NULL,
    [Value23]                    FLOAT (53)    NULL,
    [Value24]                    FLOAT (53)    NULL,
    [Value25]                    FLOAT (53)    NULL,
    [Value26]                    FLOAT (53)    NULL,
    [Value27]                    FLOAT (53)    NULL,
    [Value28]                    FLOAT (53)    NULL,
    [Value29]                    FLOAT (53)    NULL,
    [Value30]                    FLOAT (53)    NULL,
    [Value31]                    FLOAT (53)    NULL,
    [Value32]                    FLOAT (53)    NULL,
    [Value33]                    FLOAT (53)    NULL,
    [Value34]                    FLOAT (53)    NULL,
    [Value35]                    FLOAT (53)    NULL,
    [Value36]                    FLOAT (53)    NULL,
    [Value37]                    FLOAT (53)    NULL,
    [Value38]                    FLOAT (53)    NULL,
    [Value39]                    FLOAT (53)    NULL,
    [Value40]                    FLOAT (53)    NULL,
    [Value41]                    FLOAT (53)    NULL,
    [Value42]                    FLOAT (53)    NULL,
    [Value43]                    FLOAT (53)    NULL,
    [Value44]                    FLOAT (53)    NULL,
    [Value45]                    FLOAT (53)    NULL,
    [Value46]                    FLOAT (53)    NULL,
    [Value47]                    FLOAT (53)    NULL,
    [Value48]                    FLOAT (53)    NULL,
    [Value49]                    FLOAT (53)    NULL,
    [Value50]                    FLOAT (53)    NULL,
    [Flag1]                      BIT           NULL,
    [Flag2]                      BIT           NULL,
    [Flag3]                      BIT           NULL,
    [Flag4]                      BIT           NULL,
    [Flag5]                      BIT           NULL,
    [Flag6]                      BIT           NULL,
    [Flag7]                      BIT           NULL,
    [Flag8]                      BIT           NULL,
    [Flag9]                      BIT           NULL,
    [Flag10]                     BIT           NULL,
    [Minimum squeeze factor X]   FLOAT (53)    NULL,
    [Minimum squeeze factor Y]   FLOAT (53)    NULL,
    [Minimum squeeze factor Z]   FLOAT (53)    NULL,
    [Maximum squeeze factor X]   FLOAT (53)    NULL,
    [Maximum squeeze factor Y]   FLOAT (53)    NULL,
    [Maximum squeeze factor Z]   FLOAT (53)    NULL,
    [Squeeze/expand units only]  BIT           NULL,
    [Combined Performance Index] FLOAT (53)    NULL,
    [PartID]                     VARCHAR (50)  NULL,
    [Status]                     VARCHAR (50)  NULL,
    [Created by]                 VARCHAR (100) NULL,
    [Date created]               DATETIME      NULL,
    [Modified by]                VARCHAR (100) NULL,
    [Date modified]              DATETIME      NULL,
    [Date pending]               DATETIME      NULL,
    [Date effective]             DATETIME      NULL,
    [Date finished]              DATETIME      NULL,
    [Date1]                      DATETIME      NULL,
    [Date2]                      DATETIME      NULL,
    [Date3]                      DATETIME      NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

