CREATE TABLE [dbo].[PRICES_BY_DATE] (
    [rowid]                VARCHAR (20)    NULL,
    [Store]                VARCHAR (20)    NULL,
    [UPC_PLU]              VARCHAR (20)    NULL,
    [UOM]                  VARCHAR (10)    NULL,
    [From_Date]            DATE            NULL,
    [From_Time]            VARCHAR (20)    NULL,
    [Happy_Hour_From_Time] VARCHAR (20)    NULL,
    [Happy_Hour_To_Time]   VARCHAR (20)    NULL,
    [Price]                DECIMAL (20, 4) NULL,
    [Done_Date]            DATE            NULL,
    [Done_Time]            VARCHAR (20)    NULL,
    [Biz_User]             VARCHAR (20)    NULL,
    [Global_Flag]          VARCHAR (20)    NULL,
    [Undo1_Price]          VARCHAR (20)    NULL,
    [Undo1_Done_Date]      VARCHAR (20)    NULL,
    [Undo1_Done_Time]      VARCHAR (20)    NULL,
    [Undo1User]            VARCHAR (20)    NULL,
    [Undo1_Global_Flag]    VARCHAR (20)    NULL,
    [Undo2_Price]          VARCHAR (20)    NULL,
    [Undo2_Done_Date]      VARCHAR (20)    NULL,
    [Undo2_Done_Time]      VARCHAR (20)    NULL,
    [Undo2User]            VARCHAR (20)    NULL,
    [Undo2_Global_Flag]    VARCHAR (20)    NULL,
    [Purge]                VARCHAR (20)    NULL,
    [EXPORTED_TO_HO]       VARCHAR (20)    NULL,
    [Promotion]            VARCHAR (20)    NULL,
    [TIMESTAMP]            DATETIME        NULL,
    [INVENTORY_VALUE]      VARCHAR (20)    NULL,
    [MIN_PRICE]            DECIMAL (20, 4) NULL,
    [MAX_PRICE]            DECIMAL (20, 4) NULL,
    [source_file_name]     VARCHAR (200)   NULL,
    [load_date]            DATETIME        NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([Store]));

