CREATE TABLE [dbo].[PROMOTION_MASTER] (
    [PromotionCode]               VARCHAR (50)    NULL,
    [PromotionType]               VARCHAR (10)    NULL,
    [Description]                 VARCHAR (200)   NULL,
    [GroupKey]                    VARCHAR (50)    NULL,
    [GroupName]                   VARCHAR (50)    NULL,
    [Qty]                         DECIMAL (20, 4) NULL,
    [PromotionPercentToAllocate]  DECIMAL (20, 4) NULL,
    [Item]                        VARCHAR (40)    NULL,
    [Type]                        VARCHAR (20)    NULL,
    [GLAcctNo]                    VARCHAR (30)    NULL,
    [DiscountType]                VARCHAR (20)    NULL,
    [DiscountValue]               VARCHAR (20)    NULL,
    [MinPurchaseType]             VARCHAR (10)    NULL,
    [MinPurchaseValue]            VARCHAR (10)    NULL,
    [RepeatType]                  VARCHAR (10)    NULL,
    [RepeatValue]                 VARCHAR (10)    NULL,
    [DiscountAppliesOn]           VARCHAR (10)    NULL,
    [IsCombo]                     VARCHAR (10)    NULL,
    [CharacteristicCode]          VARCHAR (10)    NULL,
    [Purge]                       VARCHAR (10)    NULL,
    [DoNotSendToPOS]              VARCHAR (10)    NULL,
    [EnabledMinPurchase]          VARCHAR (10)    NULL,
    [AppliedGroupCode]            VARCHAR (20)    NULL,
    [ManufacturerFundedMultiPack] VARCHAR (10)    NULL,
    [IsLoyaltyPromo]              VARCHAR (10)    NULL,
    [ValidFromDate]               DATE            NULL,
    [ValidFromTime]               VARCHAR (20)    NULL,
    [ValidToDate]                 DATE            NULL,
    [ValidToTime]                 VARCHAR (20)    NULL,
    [TIMESTAMP]                   DATETIME        NULL,
    [source_file_name]            VARCHAR (200)   NULL,
    [load_date]                   DATETIME        NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([PromotionCode]));

