CREATE TABLE [dbo].[Recons_Sales_Details] (
    [rowid]                       BIGINT          NOT NULL,
    [Recons_Key]                  NUMERIC (18)    NOT NULL,
    [Store]                       VARCHAR (5)     NOT NULL,
    [Recons_Date]                 CHAR (8)        NOT NULL,
    [Station]                     NUMERIC (5)     NOT NULL,
    [Shift]                       NUMERIC (5)     NOT NULL,
    [Code_or_UPC]                 VARCHAR (25)    NOT NULL,
    [UOM_UPC]                     VARCHAR (3)     NOT NULL,
    [Qty_sold_in_UPC_UOM]         NUMERIC (11, 4) NOT NULL,
    [Amount_Sold]                 NUMERIC (15, 4) NOT NULL,
    [Type]                        VARCHAR (1)     NOT NULL,
    [SKU]                         VARCHAR (25)    NOT NULL,
    [Quantity_in_sku_uom]         NUMERIC (11, 4) NOT NULL,
    [Number_Of_Customers]         NUMERIC (5)     NOT NULL,
    [Amount_Including_TaxIncl]    NUMERIC (15, 4) NOT NULL,
    [TaxIncl_Amount]              NUMERIC (15, 4) NOT NULL,
    [QuantitySold_In_UPC_UOM]     NUMERIC (11, 4) NOT NULL,
    [Amount_Sold_From_POS]        NUMERIC (15, 4) NOT NULL,
    [Unidentified_Item]           BINARY (1)      NOT NULL,
    [UI_Desc]                     VARCHAR (60)    NOT NULL,
    [UI_Price]                    NUMERIC (11, 4) NOT NULL,
    [UI_UPC]                      VARCHAR (25)    NOT NULL,
    [Purch_From_Till_Inter_Seq]   NUMERIC (14)    NOT NULL,
    [RcvrPO_For_Purch_From_Till]  NUMERIC (15)    NOT NULL,
    [RcvrRev_For_Purch_From_Till] NUMERIC (5)     NOT NULL,
    [Cash]                        NUMERIC (15, 4) NOT NULL,
    [Credit]                      NUMERIC (15, 4) NOT NULL,
    [Header_SKU]                  VARCHAR (25)    NOT NULL,
    [PAID_IN_OUT_CLOSED]          BINARY (1)      NOT NULL,
    [INVENTORY_VALUE]             NUMERIC (15, 4) NOT NULL,
    [RETAIL_FLAG]                 BINARY (1)      NOT NULL,
    [REFUND_AMOUNT]               NUMERIC (15, 4) NOT NULL,
    [REFUND_COUNT]                NUMERIC (5)     NOT NULL,
    [Export_Date]                 CHAR (8)        NOT NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

