CREATE TABLE [dbo].[STG_STORES] (
    [Corp_Lvl1]             VARCHAR (100) NULL,
    [Corp_Lvl1_Name]        VARCHAR (100) NULL,
    [Corp_Lvl2]             VARCHAR (100) NULL,
    [Corp_Lvl2_Name]        VARCHAR (100) NULL,
    [Corp_Lvl3]             VARCHAR (100) NULL,
    [Corp_Lvl3_Name]        VARCHAR (100) NULL,
    [Corp_Lvl4]             VARCHAR (100) NULL,
    [Corp_Lvl4_Name]        VARCHAR (100) NULL,
    [Store]                 VARCHAR (100) NULL,
    [Name]                  VARCHAR (100) NULL,
    [Adress_Line_1]         VARCHAR (250) NULL,
    [Addres_Line_2]         VARCHAR (250) NULL,
    [City]                  VARCHAR (100) NULL,
    [State]                 VARCHAR (100) NULL,
    [ZIP]                   VARCHAR (100) NULL,
    [Tel_1]                 VARCHAR (100) NULL,
    [Manager]               VARCHAR (100) NULL,
    [Fax]                   VARCHAR (100) NULL,
    [Currency]              VARCHAR (100) NULL,
    [Tax1]                  VARCHAR (100) NULL,
    [Tax2]                  VARCHAR (100) NULL,
    [Tax3]                  VARCHAR (100) NULL,
    [Tax4]                  VARCHAR (100) NULL,
    [Dealer_Operated]       VARCHAR (100) NULL,
    [NU1]                   VARCHAR (100) NULL,
    [Store_Internal_Number] VARCHAR (100) NULL,
    [Country]               VARCHAR (100) NULL,
    [Store_Tax_No]          VARCHAR (100) NULL,
    [Store_Group]           VARCHAR (100) NULL,
    [DEACTIVATED]           VARCHAR (100) NULL,
    [ACTIVATION_DATE]       VARCHAR (100) NULL,
    [TIMESTAMP]             VARCHAR (100) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([Store]));

