CREATE TABLE [dbo].[WOW_SITE_SOH_NEW] (
    [SITE_NO]      NVARCHAR (MAX) NULL,
    [SITE_NAME]    NVARCHAR (MAX) NULL,
    [SOH_DATE]     DATE           NULL,
    [ARTICLE_NO]   NVARCHAR (MAX) NULL,
    [ARTICLE_DESC] NVARCHAR (MAX) NULL,
    [BUOM]         NVARCHAR (MAX) NULL,
    [STOCK_QTY]    FLOAT (53)     NULL,
    [SIT_QTY]      FLOAT (53)     NULL,
    [FILE_NAME]    NVARCHAR (MAX) NULL,
    [LOAD_DATE]    DATETIME2 (7)  NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

