CREATE VIEW [dbo].[VW_EG_WOW_ARTICLE_TUN_SITE_VENDOR] AS SELECT
EWAE.Article_no AS ARTICLE_NUMBER, 
EWAE.EAN, 
EWAE.TUN, 
EWAE.ARTICLE_DESC WOW_ARTICLE_DESCRIPTION,
EVAE.FULL_DESCRIPTION EG_ARTICLE_DESCRIPTION, 
EWSS.Site_no SITE_NO, 
concat(concat(DWS.description,'-'),EWSS.Site_no) SITE_NAME, 
EWSS.STOCK_QTY , 
EVAE.VENDOR_NO, 
EVAE.VENDOR_NAME, 
--EVAE.FULL_DESCRIPTION EG_ARTICLE_DESCRIPTION,  
EVAE.RESTRICTED_DESCRIPTION, 
EVAE.UOM, 
EVAE.SEGMENT_NUMBER
FROM
[EG_WOW_ARTICLE_EAN] EWAE 
LEFT JOIN 
( 
select 
main.* 
from [EG_WOW_SITE_SOH] main,
(
select 
SITE_NO,ARTICLE_NO,
max(load_date) load_date 
from [EG_WOW_SITE_SOH]
group by SITE_NO,ARTICLE_NO 
) delta
where main.SITE_NO = delta.SITE_NO
and main.ARTICLE_NO = delta.ARTICLE_NO
and main.load_date = delta.load_date ) EWSS 
ON EWAE.ARTICLE_NO=EWSS.ARTICLE_NO
LEFT JOIN [EG_VENDOR_ARTICLE_EAN] EVAE 
ON EWAE.EAN=EVAE.EAN
LEFT JOIN DIM_WOW_SITE DWS
ON EWSS.Site_no = DWS.site;