CREATE VIEW [VW_WOW_ARTICLE_TUN_SITE_VENDOR]
AS select  A.Article_no, A.EAN, A.TUN,  S.Article_desc, S.Site_no, S.site_name, S.STOCK_QTY, V.VENDOR_NO, V.VENDOR_NAME, V.FULL_DESCRIPTION, V.RESTRICTED_DESCRIPTION, V.UOM, V.SEGMENT_NUMBER
from  [EXT_WOW_ARTICLE_EAN] A LEFT OUTER JOIN [EXT_SITE_SOH] S ON A.Article_no=S.Article_no
LEFT OUTER JOIN [EXT_VENDOR_ARTICLE_EAN] V ON A.TUN=V.TUN;