CREATE EXTERNAL TABLE [dbo].[EXT_WOW_ARTICLE_EAN] (
    [ARTICLE_NO] VARCHAR (50) NULL,
    [ARTICLE_DESC] VARCHAR (200) NULL,
    [EAN] VARCHAR (50) NULL,
    [TUN] VARCHAR (50) NULL
)
    WITH (
    DATA_SOURCE = [DLStorage],
    LOCATION = N'/inbound/EG_USER/WOW_ARTICLE_EAN.csv',
    FILE_FORMAT = [CsvFormatWithHeader],
    REJECT_TYPE = PERCENTAGE,
    REJECT_VALUE = 100,
    REJECT_SAMPLE_VALUE = 1000
    );

