CREATE EXTERNAL TABLE [dbo].[EXT_VENDOR_ARTICLE_EAN] (
    [VENDOR_NAME] VARCHAR (200) NULL,
    [VENDOR_NO] VARCHAR (50) NULL,
    [EFFECTIVE_DATE] VARCHAR (20) NULL,
    [TUN] VARCHAR (50) NULL,
    [EAN] VARCHAR (50) NULL,
    [FULL_DESCRIPTION] VARCHAR (200) NULL,
    [RESTRICTED_DESCRIPTION] VARCHAR (200) NULL,
    [UOM] VARCHAR (50) NULL,
    [SEGMENT_NUMBER] VARCHAR (50) NULL
)
    WITH (
    DATA_SOURCE = [DLStorage],
    LOCATION = N'/inbound/EG_USER/VENDOR_ARTICLE_EAN.csv',
    FILE_FORMAT = [CsvFormatWithHeader],
    REJECT_TYPE = PERCENTAGE,
    REJECT_VALUE = 100,
    REJECT_SAMPLE_VALUE = 1000
    );

