CREATE EXTERNAL TABLE [dbo].[EXT_PRODUCTS] (
    [Inv_Lvl1] VARCHAR (100) NULL,
    [Inv_Lvl2] VARCHAR (100) NULL,
    [Inv_Lvl3] VARCHAR (100) NULL,
    [Inv_Lvl4] VARCHAR (100) NULL,
    [SKU_Number] VARCHAR (100) NULL,
    [Name] VARCHAR (100) NULL,
    [Upper_Name] VARCHAR (100) NULL,
    [Location] VARCHAR (100) NULL,
    [Linked_UPCCode_for_MM] VARCHAR (100) NULL,
    [UOM] VARCHAR (100) NULL,
    [Rounding_Rule_Code] VARCHAR (100) NULL,
    [Short_Name_for_POS] VARCHAR (100) NULL,
    [Delay_Sending_to_POS_old] VARCHAR (100) NULL,
    [Min_Profit] VARCHAR (100) NULL,
    [Base_Profit] VARCHAR (100) NULL,
    [Max_Profit] VARCHAR (100) NULL,
    [Activation_Date] VARCHAR (100) NULL,
    [Termination_Date] VARCHAR (100) NULL,
    [Shelf_Space] VARCHAR (100) NULL,
    [Product_Type] VARCHAR (100) NULL,
    [One_All_Type_for_MM] VARCHAR (100) NULL,
    [Link_Code_Type_for_MM] VARCHAR (100) NULL,
    [Number_Per_Batch] VARCHAR (100) NULL,
    [Value_for_MM] VARCHAR (100) NULL,
    [Sales_GL] VARCHAR (100) NULL,
    [Reserve_GL] VARCHAR (100) NULL,
    [Inventory_GL] VARCHAR (100) NULL,
    [Cost_GL] VARCHAR (100) NULL,
    [Shrink_GL] VARCHAR (100) NULL,
    [Sub_Type] VARCHAR (100) NULL,
    [Cost_Group] VARCHAR (100) NULL,
    [Generated_By_Store] VARCHAR (100) NULL,
    [Fuel_Network_Code] VARCHAR (100) NULL,
    [Octane_Rating] VARCHAR (100) NULL,
    [Fuel_Density] VARCHAR (100) NULL,
    [Exported] VARCHAR (100) NULL,
    [Purge] VARCHAR (100) NULL,
    [Linked_SKU] VARCHAR (100) NULL,
    [EXPORTED_TO_HO] VARCHAR (100) NULL,
    [Number_Of_Tickets_In_Book] VARCHAR (100) NULL,
    [Starting_Ticket_Number_In_Book] VARCHAR (100) NULL,
    [TIMESTAMP] VARCHAR (100) NULL,
    [PROMO_DISCOUNT_GL] VARCHAR (100) NULL,
    [OVERRIDE_DEP_SETTING] VARCHAR (100) NULL,
    [ELIGIBLE_FOR_AWARD] VARCHAR (100) NULL,
    [BONUS_TYPE] VARCHAR (100) NULL,
    [BONUS_VALUE] VARCHAR (100) NULL,
    [PACKAGE_BREAK_FLAG] VARCHAR (100) NULL,
    [INHERIT_CHAR_CODE] VARCHAR (100) NULL,
    [BaseUnitPriceFactor] VARCHAR (100) NULL,
    [BaseUnitDescription] VARCHAR (100) NULL,
    [PreventDealerModification] VARCHAR (100) NULL,
    [CouponAsProduct] VARCHAR (100) NULL,
    [DoNotExportToPOS] VARCHAR (100) NULL,
    [PromoSalesGL] VARCHAR (100) NULL,
    [LoyaltyPromoDiscountGL] VARCHAR (100) NULL,
    [CouponDiscountGL] VARCHAR (100) NULL,
    [ExportedToStore] VARCHAR (100) NULL
)
    WITH (
    DATA_SOURCE = [DataLakeStorage],
    LOCATION = N'/enable/full_load/Products/Refined_Products_New.csv',
    FILE_FORMAT = [CsvFormatWithHeaderComma],
    REJECT_TYPE = PERCENTAGE,
    REJECT_VALUE = 100,
    REJECT_SAMPLE_VALUE = 1000
    );

