CREATE TABLE [enable].[Promotion_Master] (
    [Rin]                         BIGINT          NOT NULL,
    [PromotionCode]               NVARCHAR (15)   NOT NULL,
    [PromotionType]               INT             NOT NULL,
    [Description]                 NVARCHAR (50)   NOT NULL,
    [GroupKey]                    BIGINT          NOT NULL,
    [GroupName]                   NVARCHAR (35)   NOT NULL,
    [Qty]                         NUMERIC (10, 4) NULL,
    [PromotionPercentToAllocate]  NUMERIC (6, 3)  NULL,
    [Item]                        NVARCHAR (30)   NULL,
    [Type]                        CHAR (1)        NULL,
    [GLAcctNo]                    VARCHAR (10)    NOT NULL,
    [DiscountType]                NUMERIC (2)     NOT NULL,
    [DiscountValue]               NUMERIC (10, 4) NOT NULL,
    [MinPurchaseType]             CHAR (1)        NOT NULL,
    [MinPurchaseValue]            NUMERIC (10, 4) NOT NULL,
    [RepeatType]                  CHAR (1)        NOT NULL,
    [RepeatValue]                 INT             NOT NULL,
    [DiscountAppliesOn]           CHAR (3)        NOT NULL,
    [IsCombo]                     CHAR (1)        NULL,
    [CharacteristicCode]          CHAR (9)        NOT NULL,
    [Purge]                       CHAR (1)        NULL,
    [DoNotSendToPOS]              CHAR (1)        NULL,
    [SendtoBOS]                   CHAR (1)        NULL,
    [EnabledMinPurchase]          CHAR (1)        NULL,
    [AppliedGroupCode]            VARCHAR (25)    NOT NULL,
    [ManufacturerFundedMultiPack] BIT             NOT NULL,
    [IsLoyaltyPromo]              CHAR (1)        NULL,
    [ValidFromDate]               CHAR (8)        NOT NULL,
    [ValidFromTime]               CHAR (6)        NOT NULL,
    [ValidToDate]                 CHAR (8)        NOT NULL,
    [ValidToTime]                 CHAR (6)        NOT NULL,
    [TIMESTAMP]                   DATETIME        NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

